version: "3"

services:
  postgres:
    container_name: go-meal-record-postgres
    platform: linux/amd64
    # build: #local
    #   context: .
    #   dockerfile: ./postgres/Dockerfile
    build: postgres

    #↓production(localでは外す)
    # image: ${AWS_ECR_IMAGE_POSTGRES}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: #local
      - ./db-data:/var/lib/postgresql/data
    ports :
      - "5432:5432"

  app:
    container_name: go-meal-record-app
    platform: linux/amd64
    # build: #local
    #   context: .
    #   dockerfile: ./app/Dockerfile
    build:
      context: ./app
      dockerfile: ./Dockerfile.development
      #上はcontextから見ての位置
    #↓production(localでは外す)
    # image: ${AWS_ECR_IMAGE_APP}
    ports:
      - "3000:3000"
    tty: true #local
    volumes: #local
      - .:/go/src/go-meal-record
    depends_on:
      - "postgres"

  nginx:
    container_name: go-meal-record-nginx
    platform: linux/amd64
    # build: #local
    #   context: .
    #   dockerfile: ./nginx/Dockerfile
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.development
      #上はcontextから見ての位置
    # ↓production(localでは外す)
    # image: ${AWS_ECR_IMAGE_NGINX}
    ports:
      - "80:80"
    depends_on:
      - "app"
