version: "3"

services:
  postgres:
    container_name: go-meal-record-postgres
    platform: linux/amd64
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports :
      - "5432:5432"

  test_postgres:
    container_name: go-meal-record-test-postgres
    platform: linux/amd64
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    ports :
      - "5433:5432"

  app:
    container_name: go-meal-record-app
    platform: linux/amd64
    build:
      context: ./app
      dockerfile: ./Dockerfile.development
      #上はcontextから見ての位置
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - .:/go/src/go-meal-record
    depends_on:
      - "postgres"

  nginx:
    container_name: go-meal-record-nginx
    platform: linux/amd64
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.development
      #上はcontextから見ての位置
    ports:
      - "80:80"
    depends_on:
      - "app"
