version: "3"

services:
  app:
    container_name: go_meal_record_app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - .:/go/src/go_meal_record

  postgres:
    container_name: go_meal_record_postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports :
      - "5432:5432"

  nginx:
    container_name: go_meal_record_nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - "app"