version: "3"
services:
  postgres:
    container_name: go_meal_record_postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    ports :
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_meal_record_app
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - .:/go/src/app