version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17
      - image: cimg/postgres:14.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
    working_directory: ~/go-meal-record
    steps:
      - checkout
      - run:
          working_directory: app #appディレクトリに移動
          name: build
          command: go build main.go
    environment:
      GO_ENVIRONMENT: development
      CGO_ENABLED: 0

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build