version: 2.1

orbs:
  go: circleci/go@1.7.0
jobs:
  build:
    docker:
      - image: cimg/go:1.17
      - image: cimg/postgres:14.4
        environment:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
    working_directory: ~/go-meal-record
    steps:
      - checkout
      # - go/mod-download-cached
      # - run:
      #     name: go mod init #go mod initしないとエラー
      #     command: go mod init
      - run:
          name: go build
          command: go build ./app/main.go

    environment:
      GOPATH: /
      GO_ENVIRONMENT: development
      CGO_ENABLED: 0

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build