version: 2.1

jobs:
  build: #test時もbuildと同じことするのでbuildがなぜ必要なのかわからない(共通処理も2回行われるので効果ないのでは？)
    docker:
      - image: cimg/go:1.17
      - image: cimg/postgres:14.4
        environment:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
    working_directory: ~/go-meal-record
    steps:
      - checkout

  test:
    docker:
      - image: cimg/go:1.17
      - image: cimg/postgres:14.4
        environment:
            POSTGRES_USER: test_user
            POSTGRES_PASSWORD: test_password
            POSTGRES_DB: test_db
    working_directory: ~/go-meal-record
    steps:
      - checkout
      - run:
          working_directory: app/test #appディレクトに移動
          name: go test
          command: go test -v
    environment:
      GO_ENVIRONMENT: development
      CGO_ENABLED: 0


workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build