version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17
      - image: cimg/postgres:14.4
    working_directory: ~/go-meal-record
    steps:
      - checkout
      - run:
          name: go mod init #go mod initしないとエラー
          command: go mod init
      - run:
          name: go build
          command: go build main.go ./app

    environment:
      GO_ENVIRONMENT: development
      CGO_ENABLED: 0

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build