# image取得(容量が小さいalpineを選択)
FROM golang:1.17.6-alpine

# ホストのファイルをコンテナの作業ディレクトリにコピー
# 下の.はdocker-composeでcontextを.としているためdocker-composeのある階層になってる
COPY . /go/src/go-meal-record/app

# ワーキングディレクトリの設定
WORKDIR /go/src/go-meal-record/app

ENV GO_ENVIRONMENT development
#コンテナ使用時test失敗するので対処として下
ENV CGO_ENABLED 0
